feature: TableKey takes into account the class name
FriendsOfCake/fixturize pull request #28
Opened 2024-08-08 13:26 UTC by krugerman007

We have the problem that you cannot load 2 fixtures for one table one after the other. For example:

- we load a fixture with 2 rows (Students\UsersFixture),
- the table with 2 rows has not been changed,
- we load a fixture for the same table but with 5 rows (Teachers\UsersFixture).

Th last fixture is not applied because the hash was not changed. And the plugin only checks the hash of the table by `connection` and `table name`. The plugin does not take into account the class name of fixtures.

2024-08-08 15:33 UTC, ravage84 commented
I can confirm that behavior.

@krugerman007 and found this while debugging some strange behavior of our large test suite.

2024-08-08 15:34 UTC, ravage84 requested changes

2024-08-08 15:34 UTC, ravage84 commented on src/TestSuite/Fixture/ChecksumTestFixture.php
> +        return $this->connection() . '-' . $this->table . '-' . static::class;
It would be good to have a test for that.

2024-08-08 15:47 UTC, ravage84 commented
@krugerman007 a heads up from my side:
The source/target branch you chose is meant for future version of the plugin which are compatible with PHP 8.1 & CakePHP 5.x

https://github.com/FriendsOfCake/fixturize/blob/896b79d76a616f70b0a5bf41b918511c7a81603f/composer.json#L47-L48

If you want to fix this for our CakePHP 3.x application, please provide an additional pull request based on/targeting the [1.xbranch](https://github.com/FriendsOfCake/fixturize/tree/1.x), which I re-created based on the last 1.x release ([1.0.3](https://github.com/FriendsOfCake/fixturize/tree/1.0.3)).

2024-08-09 08:22 UTC, krugerman007 commented
Tank you @ravage84! The PR for 1.x is there: https://github.com/FriendsOfCake/fixturize/pull/29

2024-08-09 10:26 UTC, ravage84 commented on src/TestSuite/Fixture/ChecksumTestFixture.php
> +        return $this->connection() . '-' . $this->table . '-' . static::class;
Currently, there are not tests.

Thus, it's acceptable for this PR to not add some.

2024-08-09 10:27 UTC, ravage84 commented
Please, sync any additional changes to the other PR https://github.com/FriendsOfCake/fixturize/pull/29 to here, once accepted.

2024-08-09 13:24 UTC, ravage84 commented
@krugerman007 please sync changes from #30 into this.

2024-08-09 14:11 UTC, ravage84 approved these changes
Thanks! 🚀

2024-08-09 14:12 UTC, merged